// pages/timeline.vue
<template>
<div class="page">
  <div class="page-container">
<section class="timeline">
  <ul>
    <li>
      <div>
        <time>2004</time> Geburt
      </div>
    </li>
    <li>
      <div>
        <time>2020</time> Realschulabschluss
      </div>
    </li>
  </ul>
</section>
</div>
</div>
</template>

<style lang="scss" scoped>
*,
*::before,
*::after {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font: normal 16px/1.5 "Helvetica Neue", sans-serif;
  overflow-x: hidden;
  padding-bottom: 50px;
}

.intro {
  background: #F45B69;
  padding: 100px 0;
}

.container {
  width: 90%;
  max-width: 1200px;
  margin: 0 auto;
  text-align: center;
}

h1 {
  font-size: 2.5rem;
}

.timeline ul {
  padding: 50px 0;
}

.timeline ul li {
  list-style-type: none;
  position: relative;
  width: 6px;
  margin: 0 auto;
  padding-top: 50px;
  background: #fff;
  
}

.timeline ul li::after {
  content: '';
  position: absolute;
  left: 50%;
  bottom: 0;
  transform: translateX(-50%);
  width: 30px;
  height: 30px;
  border-radius: 50%;
  background: inherit;
}

.timeline ul li div {
  position: relative;
  bottom: 0;
  width: 300px;
  padding: 15px;
  background: #F45B69;
}

.timeline ul li div::before {
  content: '';
  position: absolute;
  bottom: 7px;
  width: 0;
  height: 0;
  border-style: solid;
}

.timeline ul li:nth-child(odd) div {
  left: 45px;
}

.timeline ul li:nth-child(odd) div::before {
  left: -15px;
  border-width: 8px 16px 8px 0;
  border-color: transparent #F45B69 transparent transparent;
}

.timeline ul li:nth-child(even) div {
  left: -439px;
}

.timeline ul li:nth-child(even) div::before {
  right: -15px;
  border-width: 8px 0 8px 16px;
  border-color: transparent transparent transparent #F45B69;
}

time {
  display: block;
  font-size: 1.2rem;
  font-weight: bold;
  margin-bottom: 8px;
}

.timeline ul li::after {
  transition: background .5s ease-in-out;
}

.timeline ul li.in-view::after {
  background: #F45B69;
}

.timeline ul li div {
  transition: all .5s ease-in-out;
}

.timeline ul div {
  transform: translate3d(50px, 0, 0);
}

@media screen and (max-width: 900px) {
  .timeline ul li div {
    width: 250px;
  }
  .timeline ul li:nth-child(even) div {
    left: -289px;
    /*250+45-6*/
  }
}

@media screen and (max-width: 600px) {
  .timeline ul li {
    margin-left: 20px;
  }
  .timeline ul li div {
    width: calc(100vw - 91px);
  }
  .timeline ul li:nth-child(even) div {
    left: 45px;
  }
  .timeline ul li:nth-child(even) div::before {
    left: -15px;
    border-width: 8px 16px 8px 0;
    border-color: transparent #F45B69 transparent transparent;
  }
}


.page {
  left: 0;
  top: 0;
  height: 100%;
  width: 100%;

  display: flex;
  position: absolute;

  align-items: center;
  justify-content: center;

  .page-container {
    text-align: left;
    width: 90vw;
    max-height: 75vh;

    padding: 12px;
    border-radius: 2px;

    background-color: rgba(236, 240, 241, 0.8);
    color: black;

    overflow: auto;
  }
}
</style>

<script>
export default {
    name: 'Timeline',
}
</script>

// src/components/svelte/Timeline.svelte
<div class="timeline">
  <div class="container right">
    <div class="content">
      <h2>2022 - jetzt</h2>
      <p>Software-Entwickler</p>
    </div>
  </div>
  <div class="container left">
    <div class="content">
      <h2>2020 - 2022</h2>
      <p>Ausbildung zum Fachinformatiker (Anwendungsentwicklung)</p>
    </div>
  </div>
  <div class="unimportant container right">
    <div class="content">
      <h2>2020</h2>
      <p>Realschulabschluss</p>
    </div>
  </div>
</div>

<style lang="scss">
  .unimportant > .content {
    & > h2 {
      font-size: 1.5rem;
    }

    & > p {
      font-size: 0.8rem;
    }
  }

  /* The actual timeline (the vertical ruler) */
  .timeline {
    position: relative;
    max-width: 1200px;
    margin: 0 auto;
  }

  /* The actual timeline (the vertical ruler) */
  .timeline::after {
    content: "";
    position: absolute;
    width: 6px;
    background-color: black;
    top: 0;
    bottom: 0;
    left: 50%;
    margin-left: -3px;
  }

  /* Container around content */
  .container {
    padding: 10px 40px;
    position: relative;
    background-color: inherit;
    width: 50%;
  }

  /* The circles on the timeline */
  .container::after {
    content: "";
    position: absolute;
    width: 25px;
    height: 25px;
    right: -17px;
    background-color: white;
    border: 4px solid gray;
    top: 15px;
    border-radius: 50%;
    z-index: 1;
  }

  /* Place the container to the left */
  .container:nth-child(even) {
    left: 0;
  }

  /* Place the container to the right */
  .container:nth-child(odd) {
    left: 50%;
  }

  /* Add arrows to the left container (pointing right) */
  .container:nth-child(even)::before {
    content: " ";
    height: 0;
    position: absolute;
    top: 22px;
    width: 0;
    z-index: 1;
    right: 30px;
    border: medium solid white;
    border-width: 10px 0 10px 10px;
    border-color: transparent transparent transparent white;
  }

  /* Add arrows to the right container (pointing left) */
  .container:nth-child(odd)::before {
    content: " ";
    height: 0;
    position: absolute;
    top: 22px;
    width: 0;
    z-index: 1;
    left: 30px;
    border: medium solid white;
    border-width: 10px 10px 10px 0;
    border-color: transparent white transparent transparent;
  }

  /* Fix the circle for containers on the right side */
  .container:nth-child(odd)::after {
    left: -16px;
  }

  /* The actual content */
  .content {
    padding: 20px 30px;
    background-color: white;
    position: relative;
    border-radius: 6px;
  }

  /* Media queries - Responsive timeline on screens less than 600px wide */
  @media screen and (max-width: 600px) {
    /* Place the timelime to the left */
    .timeline::after {
      left: 31px;
    }

    /* Full-width containers */
    .container {
      width: 100%;
      padding-left: 70px;
      padding-right: 25px;
    }

    /* Make sure that all arrows are pointing leftwards */
    .container::before {
      left: 60px;
      border: medium solid white;
      border-width: 10px 10px 10px 0;
      border-color: transparent white transparent transparent;
    }

    /* Make sure all circles are at the same spot */
    .container:nth-child(even)::after,
    .container:nth-child(odd)::after {
      left: 15px;
    }

    /* Make all right containers behave like the left ones */
    .container:nth-child(odd) {
      left: 0%;
    }
  }
</style>
